services:
  - type: web
    name: odoo-19
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000